# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

strategy:
  matrix:
    linux:
      imageName: 'Ubuntu-16.04'
    mac:
      imageName: 'macOS-10.13'
    windows:
      imageName: 'win1803'

pool:
  vmImage: $(imageName)

steps:
- task: NodeTool@0
  displayName: 'Install Node.js'
  inputs:
    versionSpec: '10.x'

- task: Npm@1
  displayName: 'Install Packages'
  inputs:
    command: install
    

# install mocha-junit-reporter
- task: Npm@0
  displayName: 'Install mocha-junit-reporter'
  inputs:
    command: custom
    customCommand: install -g mocha-junit-reporter && npm run build-client && PERCY_TOKEN=abc mocha --forbid-only \"test/**/*.test.ts\" --exclude \"test/percy-agent-client/**/*.test.ts\" --exclude \"test/integration/**/*\" --reporter mocha-junit-reporter

# will need to install the reporter on the project
# - task: Npm@0
#   displayName: 'WIP Test runner'
#   inputs:
#     command: npm run build-client && PERCY_TOKEN=abc mocha --forbid-only \"test/**/*.test.ts\" --exclude \"test/percy-agent-client/**/*.test.ts\" --exclude \"test/integration/**/*\" --reporter mocha-junit-reporter

# - task: Npm@0
#   displayName: 'Run Tests'
#   inputs:
#     command: test

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
    testRunTitle: 'Test results for JavaScript'
