# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

strategy:
  matrix:
    linux:
      imageName: 'Ubuntu-16.04'
    mac:
      imageName: 'macOS-10.13'
    windows:
      imageName: 'win1803'

pool:
  vmImage: $(imageName)

variables:
  LOG_LEVEL: debug

steps:
- task: NodeTool@0
  displayName: 'Install Node.js'
  inputs:
    versionSpec: '10.x'

- script: |
    npm ci
    npm run build-client
    npm run test --reporter mocha-junit-reporter
    npm run test-integration
  displayName: 'install, build and test'
